dist: trusty
language: c
sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Z4RvBipmS/iF7ZkDJFUTWi3eULQ5TxaCVf98xWmwW8F/Jciknimx34EK2Ooikb71wdHnTE3zu0+ohpk31htuZrJ2hBgCtnC7WkVIwQ61SZViFkYfhGSsADTZXgvewNkwwKUTW9Nh1Vqpo37YxhPmxcVrkXf8ySgX9pk53i7dmEivp6j6X8UmXom35Prnp0/J5eW2pn33JyKh2c/5fKosP/LYkvV6IWrXOUnz+5tCXD8AOtiJ2ekdvo0FLUJU4Xyilw70pnW+ocrVf3MFOhQCIR17mZCcxFkQVxVep60y75rfQnks0A0KwSBX8Ylxe+X4qwa4wvtSD98jXwg00w7bFQsOyN1Pxfljjz0Q6mc2cSwznf0VtMNbfQEs1yZT+3Wj8f9hBs8IppSqmU6H7aN3NotT2f9RfHgHOMq2Fuvn3kdVUvlCmoX/fNx3vwMWgcRKYiMADu3VRfb8XBV0MgNZlnqHkSSAD6TnvXG7of5Gno0VwJwHoqsl3KKmhnfmOTze3I0Al1VM76cDRjrDHOlUZTpmnnptJ7n9RUK9OH/HYTSriYc6V4tLfFQC8fNdfWBrR641t127Kqe3zMRog/sR+y2SP+mBAf4jKke9JxdxxOpgkS6ld+qfSg4b2wWdX9YXX/Z/W2NPJb7m3URXiSQtY+ZpCP8gpl91V7eyxq7L89I="

before_install:
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install libmpfr-dev clang-3.5 llvm-3.5 llvm-3.5-dev dragonegg-4.7 gcc-4.7 g++-4.7 gfortran-4.7 libgfortran-4.7-dev autoconf automake build-essential libedit-dev python3-dev cython3 binutils
  - echo -n | openssl s_client -connect scan.coverity.com:443 -CApath /etc/ssl/certs/  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  apt:
    coverity_scan:
      project:
        name: yohanchatelain/verificarlo
        description: A tool for automatic Montecarlo Arithmetic analysis.
      notification_email: yohan.chatelain@gmail.com
      build_command_prepend: ./configure --with-llvm=/usr/lib/llvm-3.5/bin/ --with-dragonegg=/usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/dragonegg.so CC=gcc-4.7 CXX=g++-4.7
      build_command: make
      branch_pattern: coverity-travis-CI

install:
  - ./autogen.sh
  - export LIBRARY_PATH=/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib/../lib64:/usr/lib/x86_64-linux-gnu:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../..:/usr/lib/llvm-3.5/bin/../lib:/lib:/usr/lib:$LIBRARY_PATH
  - ./configure --with-llvm=/usr/lib/llvm-3.5/bin/ --with-dragonegg=/usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/dragonegg.so CC=gcc-4.7 CXX=g++-4.7 || cat config.log
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=/usr/local/lib/python3.4/site-packages/:$PYTHONPATH

script:
  - cat /home/travis/build/yohanchatelain/verificarlo/cov-int/scm_log.txt
  - make installcheck
  - for i in $(find tests/ -maxdepth 1 -type d -name 'test_*' | sort ); do echo "************** TEST $i"; cat $i/test.log; done;

