dist: trusty
language: c
sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SGviO+A60+RYLJF2oCGKUzFaOHOQKrni3YBLbv+h7XV0hnZE8LiZVG8MUG1veveR80MBkX7JxA+Kz30ikHOC30dS5h5FsuwoobEDvlXdzUDtmWyI6RcLuAEHr1+VRFRmRBZgdunL0s2apDpVjQyK9lf+2h/vNH9KP7XkAGlxBQmVZ1oUXvmOkwBQFnOeXbdYqnCJ3+9m9KyOw6eT0TPjejPQnWHbVdFcVGppZ/n6W1F3cbg6SP7i/8fLo3UpjnrcWpWsKwxArjFIZzGf7iwWcqJHto1dQg/6GFwXc+Bb7sHDIvu75MmG3xFXl6ZKt71fFFKxN+LW8zVJ8haAfKOOR5FdrEpdBD468hU07kI1PA65Roxg/HQLHIJLC53IFFoSrucNed88xX3DotR16P1OQLcchL//2M7Oh+o5F7lSbdkBj4YiHNYicL0yzBhNdsBO9N7Sk2KJWYWs2jZt484TALtNadtU7ZSeLrtgVHqteAXOcm+Xjk6Su5Hs4rlEK5Ng0xoL7XTHP8ynLc5qBLxZA0u5dh4FL3ZJ/de6x/ZThT6g/CHVGiqCMuy55xWnjtMCRpnfEIZc7d+KLdRkxojZ0B6hSMA7kzJU7SwYlUnV7EVr6F2xO+JSIBCC7+NbXqP2Yfnm/9qbMF5Ho5E/POjluoEMjv7iBp8ZZ9nSWLrRTPY="

before_install:
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install libmpfr-dev clang-3.5 llvm-3.5 llvm-3.5-dev dragonegg-4.7 gcc-4.7 g++-4.7 gfortran-4.7 libgfortran-4.7-dev autoconf automake build-essential libedit-dev python3-dev cython3 binutils
  - echo -n | openssl s_client -connect scan.coverity.com:443 -CApath /etc/ssl/certs/  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  coverity_scan:
    project:
      name: "yohanchatelain/verificarlo"
      description: "A tool for automatic Montecarlo Arithmetic analysis."
    notification_email: yohan.chatelain@gmail.com
    build_command_prepend: 
    build_command: "cov-build --dir=cov-int --include-instrumentation-path $HOME/build/yohanchatelain/verificarlo/src make"
    branch_pattern: coverity-travis-CI

install:
  - ./autogen.sh
  - export LIBRARY_PATH=/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu:/lib/x86_64-linux-gnu:/lib/../lib64:/usr/lib/x86_64-linux-gnu:/usr/bin/../lib/gcc/x86_64-linux-gnu/4.7/../../..:/usr/lib/llvm-3.5/bin/../lib:/lib:/usr/lib:$LIBRARY_PATH
  - ./configure --with-llvm=/usr/lib/llvm-3.5/bin/ --with-dragonegg=/usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/dragonegg.so CC=gcc-4.7 CXX=g++-4.7 || cat config.log
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=/usr/local/lib/python3.4/site-packages/:$PYTHONPATH
  - make clean

script:
  - cat /home/travis/build/yohanchatelain/verificarlo/cov-int/scm_log.txt
  - cat /home/travis/build/yohanchatelain/verificarlo/cov-int/build-log.txt
  - make installcheck
  - for i in $(find tests/ -maxdepth 1 -type d -name 'test_*' | sort ); do echo "************** TEST $i"; cat $i/test.log; done;

