sut:
  build: .
    command: make -C /build/verificarlo installcheck
    dockerfile: Dockerfile
sut-16_04:
  build: .
    command: make -C /build/verificarlo installcheck
    dockerfile: Dockerfile-16.04