dot:
	verificarlo --exclude-file=dot_fct.txt dot_product.c -o dot_product -lm --verbose -O0 --tracer --tracer-level=temporary --tracer-backtrace

dot-txt:
	verificarlo --exclude-file=dot_fct.txt dot_product.c -o dot_product -lm --verbose -O0 --tracer --tracer-level=temporary --tracer-backtrace --tracer-format=text

clean:
	rm *.ll *.o

